INSERT INTO "Role" (slug, weight) VALUES
  ('admin', 100),
  ('client', 20),
  ('clientRepresentative', 10),
  ('complianceManager', 50),
  ('accountant', 50),
  ('salesManager', 40),
  ('seniorSalesManager', 60),
  ('headOfSales', 70),
  ('financialAnalyst', 30),
  ('trustee', 25),
  ('branchManager', 55),
  ('headOfBranch', 65),
  ('marketer', 25),
  ('partnerManager', 45),
  ('partner', 20),
  ('partnerRepresentative', 10);
