name: erp-modul
services:
  erp-modul.spa:
    image: 'spa_image'
    container_name: erp-modul.spa
    restart: unless-stopped
    networks:
      - erpmodul_network

  erp-modul.storybook:
    image: 'storybook_image'
    container_name: erp-modul.storybook
    restart: unless-stopped
    networks:
      - erpmodul_network

networks:
  erpmodul_network:
    external: true
