// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users-service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOwnerRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	TenantID             string   `protobuf:"bytes,5,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOwnerRequest) Reset()         { *m = CreateOwnerRequest{} }
func (m *CreateOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOwnerRequest) ProtoMessage()    {}
func (*CreateOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{0}
}

func (m *CreateOwnerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOwnerRequest.Unmarshal(m, b)
}
func (m *CreateOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOwnerRequest.Marshal(b, m, deterministic)
}
func (m *CreateOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOwnerRequest.Merge(m, src)
}
func (m *CreateOwnerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOwnerRequest.Size(m)
}
func (m *CreateOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOwnerRequest proto.InternalMessageInfo

func (m *CreateOwnerRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateOwnerRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateOwnerRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateOwnerRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateOwnerRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

type CreateOwnerResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOwnerResponse) Reset()         { *m = CreateOwnerResponse{} }
func (m *CreateOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOwnerResponse) ProtoMessage()    {}
func (*CreateOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{1}
}

func (m *CreateOwnerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOwnerResponse.Unmarshal(m, b)
}
func (m *CreateOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOwnerResponse.Marshal(b, m, deterministic)
}
func (m *CreateOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOwnerResponse.Merge(m, src)
}
func (m *CreateOwnerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOwnerResponse.Size(m)
}
func (m *CreateOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOwnerResponse proto.InternalMessageInfo

func (m *CreateOwnerResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetUserRequest struct {
	TenantID             string   `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	ID                   uint32   `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{2}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *GetUserRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetUserResponse struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{3}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *GetUserResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *GetUserResponse) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *GetUserResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetUsersByIDRequest struct {
	TenantID             string   `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	IDs                  []uint32 `protobuf:"varint,2,rep,packed,name=IDs,proto3" json:"IDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersByIDRequest) Reset()         { *m = GetUsersByIDRequest{} }
func (m *GetUsersByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersByIDRequest) ProtoMessage()    {}
func (*GetUsersByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{4}
}

func (m *GetUsersByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByIDRequest.Unmarshal(m, b)
}
func (m *GetUsersByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByIDRequest.Merge(m, src)
}
func (m *GetUsersByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersByIDRequest.Size(m)
}
func (m *GetUsersByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByIDRequest proto.InternalMessageInfo

func (m *GetUsersByIDRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *GetUsersByIDRequest) GetIDs() []uint32 {
	if m != nil {
		return m.IDs
	}
	return nil
}

type GetUsersByIDResponse struct {
	Users                []*GetUserResponse `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetUsersByIDResponse) Reset()         { *m = GetUsersByIDResponse{} }
func (m *GetUsersByIDResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersByIDResponse) ProtoMessage()    {}
func (*GetUsersByIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{5}
}

func (m *GetUsersByIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersByIDResponse.Unmarshal(m, b)
}
func (m *GetUsersByIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersByIDResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersByIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersByIDResponse.Merge(m, src)
}
func (m *GetUsersByIDResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersByIDResponse.Size(m)
}
func (m *GetUsersByIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersByIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersByIDResponse proto.InternalMessageInfo

func (m *GetUsersByIDResponse) GetUsers() []*GetUserResponse {
	if m != nil {
		return m.Users
	}
	return nil
}

type Permissions struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Models               []uint32 `protobuf:"varint,2,rep,packed,name=Models,proto3" json:"Models,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permissions) Reset()         { *m = Permissions{} }
func (m *Permissions) String() string { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()    {}
func (*Permissions) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{6}
}

func (m *Permissions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permissions.Unmarshal(m, b)
}
func (m *Permissions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permissions.Marshal(b, m, deterministic)
}
func (m *Permissions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permissions.Merge(m, src)
}
func (m *Permissions) XXX_Size() int {
	return xxx_messageInfo_Permissions.Size(m)
}
func (m *Permissions) XXX_DiscardUnknown() {
	xxx_messageInfo_Permissions.DiscardUnknown(m)
}

var xxx_messageInfo_Permissions proto.InternalMessageInfo

func (m *Permissions) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Permissions) GetModels() []uint32 {
	if m != nil {
		return m.Models
	}
	return nil
}

type PermissionsEdit struct {
	ID                   uint32         `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Permissions          []*Permissions `protobuf:"bytes,2,rep,name=Permissions,proto3" json:"Permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PermissionsEdit) Reset()         { *m = PermissionsEdit{} }
func (m *PermissionsEdit) String() string { return proto.CompactTextString(m) }
func (*PermissionsEdit) ProtoMessage()    {}
func (*PermissionsEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{7}
}

func (m *PermissionsEdit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionsEdit.Unmarshal(m, b)
}
func (m *PermissionsEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionsEdit.Marshal(b, m, deterministic)
}
func (m *PermissionsEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionsEdit.Merge(m, src)
}
func (m *PermissionsEdit) XXX_Size() int {
	return xxx_messageInfo_PermissionsEdit.Size(m)
}
func (m *PermissionsEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionsEdit.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionsEdit proto.InternalMessageInfo

func (m *PermissionsEdit) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PermissionsEdit) GetPermissions() []*Permissions {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type MultiplePermissionsEditRequest struct {
	TenantID             string             `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	PermissionsList      []*PermissionsEdit `protobuf:"bytes,2,rep,name=PermissionsList,proto3" json:"PermissionsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MultiplePermissionsEditRequest) Reset()         { *m = MultiplePermissionsEditRequest{} }
func (m *MultiplePermissionsEditRequest) String() string { return proto.CompactTextString(m) }
func (*MultiplePermissionsEditRequest) ProtoMessage()    {}
func (*MultiplePermissionsEditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{8}
}

func (m *MultiplePermissionsEditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplePermissionsEditRequest.Unmarshal(m, b)
}
func (m *MultiplePermissionsEditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplePermissionsEditRequest.Marshal(b, m, deterministic)
}
func (m *MultiplePermissionsEditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplePermissionsEditRequest.Merge(m, src)
}
func (m *MultiplePermissionsEditRequest) XXX_Size() int {
	return xxx_messageInfo_MultiplePermissionsEditRequest.Size(m)
}
func (m *MultiplePermissionsEditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplePermissionsEditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplePermissionsEditRequest proto.InternalMessageInfo

func (m *MultiplePermissionsEditRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *MultiplePermissionsEditRequest) GetPermissionsList() []*PermissionsEdit {
	if m != nil {
		return m.PermissionsList
	}
	return nil
}

type MultiplePermissionsEditResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiplePermissionsEditResponse) Reset()         { *m = MultiplePermissionsEditResponse{} }
func (m *MultiplePermissionsEditResponse) String() string { return proto.CompactTextString(m) }
func (*MultiplePermissionsEditResponse) ProtoMessage()    {}
func (*MultiplePermissionsEditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{9}
}

func (m *MultiplePermissionsEditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiplePermissionsEditResponse.Unmarshal(m, b)
}
func (m *MultiplePermissionsEditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiplePermissionsEditResponse.Marshal(b, m, deterministic)
}
func (m *MultiplePermissionsEditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiplePermissionsEditResponse.Merge(m, src)
}
func (m *MultiplePermissionsEditResponse) XXX_Size() int {
	return xxx_messageInfo_MultiplePermissionsEditResponse.Size(m)
}
func (m *MultiplePermissionsEditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiplePermissionsEditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiplePermissionsEditResponse proto.InternalMessageInfo

func (m *MultiplePermissionsEditResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckAccessRequest struct {
	TenantID             string   `protobuf:"bytes,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	PermName             string   `protobuf:"bytes,2,opt,name=permName,proto3" json:"permName,omitempty"`
	UserID               uint32   `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	ModelIDs             []uint32 `protobuf:"varint,4,rep,packed,name=modelIDs,proto3" json:"modelIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckAccessRequest) Reset()         { *m = CheckAccessRequest{} }
func (m *CheckAccessRequest) String() string { return proto.CompactTextString(m) }
func (*CheckAccessRequest) ProtoMessage()    {}
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{10}
}

func (m *CheckAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccessRequest.Unmarshal(m, b)
}
func (m *CheckAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccessRequest.Marshal(b, m, deterministic)
}
func (m *CheckAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccessRequest.Merge(m, src)
}
func (m *CheckAccessRequest) XXX_Size() int {
	return xxx_messageInfo_CheckAccessRequest.Size(m)
}
func (m *CheckAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccessRequest proto.InternalMessageInfo

func (m *CheckAccessRequest) GetTenantID() string {
	if m != nil {
		return m.TenantID
	}
	return ""
}

func (m *CheckAccessRequest) GetPermName() string {
	if m != nil {
		return m.PermName
	}
	return ""
}

func (m *CheckAccessRequest) GetUserID() uint32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CheckAccessRequest) GetModelIDs() []uint32 {
	if m != nil {
		return m.ModelIDs
	}
	return nil
}

type AccessByModelID struct {
	HasAccess            bool     `protobuf:"varint,1,opt,name=hasAccess,proto3" json:"hasAccess,omitempty"`
	ModelID              uint32   `protobuf:"varint,2,opt,name=modelID,proto3" json:"modelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccessByModelID) Reset()         { *m = AccessByModelID{} }
func (m *AccessByModelID) String() string { return proto.CompactTextString(m) }
func (*AccessByModelID) ProtoMessage()    {}
func (*AccessByModelID) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{11}
}

func (m *AccessByModelID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccessByModelID.Unmarshal(m, b)
}
func (m *AccessByModelID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccessByModelID.Marshal(b, m, deterministic)
}
func (m *AccessByModelID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccessByModelID.Merge(m, src)
}
func (m *AccessByModelID) XXX_Size() int {
	return xxx_messageInfo_AccessByModelID.Size(m)
}
func (m *AccessByModelID) XXX_DiscardUnknown() {
	xxx_messageInfo_AccessByModelID.DiscardUnknown(m)
}

var xxx_messageInfo_AccessByModelID proto.InternalMessageInfo

func (m *AccessByModelID) GetHasAccess() bool {
	if m != nil {
		return m.HasAccess
	}
	return false
}

func (m *AccessByModelID) GetModelID() uint32 {
	if m != nil {
		return m.ModelID
	}
	return 0
}

type CheckAccessResponse struct {
	Access               []*AccessByModelID `protobuf:"bytes,1,rep,name=access,proto3" json:"access,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *CheckAccessResponse) Reset()         { *m = CheckAccessResponse{} }
func (m *CheckAccessResponse) String() string { return proto.CompactTextString(m) }
func (*CheckAccessResponse) ProtoMessage()    {}
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_86be2d66f43f08ea, []int{12}
}

func (m *CheckAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckAccessResponse.Unmarshal(m, b)
}
func (m *CheckAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckAccessResponse.Marshal(b, m, deterministic)
}
func (m *CheckAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckAccessResponse.Merge(m, src)
}
func (m *CheckAccessResponse) XXX_Size() int {
	return xxx_messageInfo_CheckAccessResponse.Size(m)
}
func (m *CheckAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckAccessResponse proto.InternalMessageInfo

func (m *CheckAccessResponse) GetAccess() []*AccessByModelID {
	if m != nil {
		return m.Access
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateOwnerRequest)(nil), "pb.CreateOwnerRequest")
	proto.RegisterType((*CreateOwnerResponse)(nil), "pb.CreateOwnerResponse")
	proto.RegisterType((*GetUserRequest)(nil), "pb.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "pb.GetUserResponse")
	proto.RegisterType((*GetUsersByIDRequest)(nil), "pb.GetUsersByIDRequest")
	proto.RegisterType((*GetUsersByIDResponse)(nil), "pb.GetUsersByIDResponse")
	proto.RegisterType((*Permissions)(nil), "pb.Permissions")
	proto.RegisterType((*PermissionsEdit)(nil), "pb.PermissionsEdit")
	proto.RegisterType((*MultiplePermissionsEditRequest)(nil), "pb.MultiplePermissionsEditRequest")
	proto.RegisterType((*MultiplePermissionsEditResponse)(nil), "pb.MultiplePermissionsEditResponse")
	proto.RegisterType((*CheckAccessRequest)(nil), "pb.CheckAccessRequest")
	proto.RegisterType((*AccessByModelID)(nil), "pb.AccessByModelID")
	proto.RegisterType((*CheckAccessResponse)(nil), "pb.CheckAccessResponse")
}

func init() { proto.RegisterFile("users-service.proto", fileDescriptor_86be2d66f43f08ea) }

var fileDescriptor_86be2d66f43f08ea = []byte{
	// 589 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xdd, 0x8e, 0xd2, 0x40,
	0x14, 0xa6, 0xe5, 0x67, 0x77, 0x0f, 0xcb, 0x62, 0xa6, 0x04, 0x1a, 0x62, 0x94, 0x8c, 0x37, 0x18,
	0x23, 0x46, 0xd4, 0x2b, 0x35, 0x11, 0xa8, 0x31, 0x4d, 0x44, 0x4d, 0xd5, 0x07, 0x28, 0x30, 0x86,
	0x46, 0x68, 0x6b, 0xcf, 0xe0, 0x66, 0xe3, 0x8d, 0x0f, 0x62, 0xe2, 0x43, 0xfa, 0x02, 0x66, 0xa6,
	0xd3, 0xd2, 0x1f, 0x41, 0xee, 0xf8, 0xce, 0xff, 0xf9, 0xe6, 0x3b, 0x05, 0x8c, 0x1d, 0xb2, 0x08,
	0x1f, 0x22, 0x8b, 0xbe, 0x7b, 0x4b, 0x36, 0x0a, 0xa3, 0x80, 0x07, 0x44, 0x0f, 0x17, 0xf4, 0x97,
	0x06, 0x64, 0x16, 0x31, 0x97, 0xb3, 0xf7, 0xd7, 0x3e, 0x8b, 0x1c, 0xf6, 0x6d, 0xc7, 0x90, 0x93,
	0x0e, 0xd4, 0xd9, 0xd6, 0xf5, 0x36, 0xa6, 0x36, 0xd0, 0x86, 0x17, 0x4e, 0x0c, 0xc8, 0x6d, 0xb8,
	0xf8, 0xe2, 0x45, 0xc8, 0xdf, 0xb9, 0x5b, 0x66, 0xea, 0xd2, 0xb3, 0x37, 0x90, 0x3e, 0x9c, 0x6f,
	0x5c, 0xe5, 0xac, 0x4a, 0x67, 0x8a, 0x85, 0x2f, 0x74, 0x11, 0xaf, 0x83, 0x68, 0x65, 0xd6, 0x62,
	0x5f, 0x82, 0x85, 0x8f, 0x33, 0xdf, 0xf5, 0xb9, 0x6d, 0x99, 0xf5, 0xd8, 0x97, 0x60, 0xfa, 0x08,
	0x8c, 0xdc, 0x74, 0x18, 0x06, 0x3e, 0x32, 0x62, 0xc2, 0x19, 0xee, 0x96, 0x4b, 0x86, 0x28, 0x07,
	0x3c, 0x77, 0x12, 0x48, 0x5f, 0xc0, 0xd5, 0x1b, 0xc6, 0x3f, 0xe3, 0x7e, 0x95, 0x6c, 0x79, 0x2d,
	0x5f, 0x9e, 0x5c, 0x81, 0x6e, 0x5b, 0x72, 0x93, 0x96, 0xa3, 0xdb, 0x16, 0xfd, 0xad, 0x41, 0x3b,
	0x4d, 0x57, 0xbd, 0xe2, 0x18, 0x2d, 0x89, 0xd9, 0x53, 0xa3, 0x1f, 0xa4, 0xa6, 0x7a, 0x8c, 0x9a,
	0x5a, 0x81, 0x9a, 0x0e, 0xd4, 0xc3, 0x75, 0xe0, 0x33, 0xb5, 0x7b, 0x0c, 0x48, 0x17, 0x1a, 0xc8,
	0x5d, 0xbe, 0x43, 0xb3, 0x21, 0xcd, 0x0a, 0xd1, 0x19, 0x18, 0x6a, 0x40, 0x9c, 0xde, 0xd8, 0xd6,
	0x29, 0x4b, 0xde, 0x82, 0xaa, 0x6d, 0xa1, 0xa9, 0x0f, 0xaa, 0xc3, 0x96, 0x23, 0x7e, 0xd2, 0x09,
	0x74, 0xf2, 0x45, 0xd4, 0xaa, 0xf7, 0xa1, 0x2e, 0x75, 0x62, 0x6a, 0x83, 0xea, 0xb0, 0x39, 0x36,
	0x46, 0xe1, 0x62, 0x54, 0xa0, 0xc3, 0x89, 0x23, 0xe8, 0x33, 0x68, 0x7e, 0x60, 0xd1, 0xd6, 0x43,
	0xf4, 0x02, 0x1f, 0x4b, 0x24, 0x75, 0xa1, 0x31, 0x0f, 0x56, 0x6c, 0x93, 0xb4, 0x55, 0x88, 0x7e,
	0x82, 0x76, 0x26, 0xed, 0xf5, 0xca, 0xe3, 0xa5, 0xd4, 0xc7, 0xb9, 0xca, 0x32, 0xbf, 0x39, 0x6e,
	0x8b, 0x51, 0x32, 0x66, 0x27, 0x1b, 0x43, 0x7f, 0xc0, 0x9d, 0xf9, 0x6e, 0xc3, 0xbd, 0x70, 0xc3,
	0x0a, 0xd5, 0x4f, 0xe1, 0xe7, 0x65, 0x6e, 0xa6, 0xb7, 0x1e, 0x72, 0xd5, 0xd4, 0x28, 0x34, 0x95,
	0x05, 0x8b, 0xb1, 0xf4, 0x39, 0xdc, 0x3d, 0xd8, 0xfc, 0xbf, 0x72, 0xfd, 0x29, 0xce, 0x6f, 0xcd,
	0x96, 0x5f, 0x27, 0x12, 0x9f, 0x32, 0xae, 0x38, 0x25, 0x16, 0x6d, 0x33, 0x37, 0x98, 0x62, 0x41,
	0xbb, 0x78, 0x1e, 0xdb, 0x92, 0x12, 0x6c, 0x39, 0x0a, 0x89, 0x9c, 0xad, 0x78, 0x00, 0xa1, 0x83,
	0x9a, 0x7c, 0x90, 0x14, 0x53, 0x1b, 0xda, 0x71, 0xf3, 0xe9, 0xcd, 0x3c, 0xb6, 0x09, 0x31, 0xaf,
	0x5d, 0x9c, 0x64, 0x27, 0xde, 0x1b, 0xc4, 0x36, 0x2a, 0x59, 0x5d, 0x4e, 0x02, 0xe9, 0x14, 0x8c,
	0xdc, 0x32, 0x6a, 0xfd, 0x07, 0xd0, 0x70, 0x93, 0x5a, 0x29, 0xaf, 0x85, 0x9e, 0x8e, 0x0a, 0x19,
	0xff, 0xd1, 0xe1, 0x52, 0x2a, 0xf3, 0x63, 0xfc, 0xad, 0x22, 0xaf, 0xa0, 0x99, 0xf9, 0x04, 0x90,
	0xae, 0x48, 0x2e, 0x7f, 0xb1, 0xfa, 0xbd, 0x92, 0x3d, 0xee, 0x4e, 0x2b, 0xe4, 0x29, 0x9c, 0x29,
	0x15, 0x13, 0x92, 0x93, 0x74, 0x9c, 0xf9, 0x2f, 0x99, 0xd3, 0x0a, 0x99, 0xc1, 0x65, 0xf6, 0x48,
	0x48, 0x2f, 0x13, 0x96, 0xbd, 0xbd, 0xbe, 0x59, 0x76, 0xa4, 0x45, 0x56, 0xd0, 0x3b, 0x20, 0x0e,
	0x42, 0x45, 0xda, 0x71, 0xd9, 0xf6, 0xef, 0x1d, 0x8d, 0x49, 0xbb, 0x08, 0x8a, 0xf6, 0xbc, 0x2b,
	0x8a, 0x4a, 0xaa, 0x52, 0x14, 0x95, 0x1f, 0x88, 0x56, 0x16, 0x0d, 0xf9, 0x8f, 0xf0, 0xe4, 0x6f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x10, 0xe4, 0xb2, 0x0a, 0x28, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	CreateOwner(ctx context.Context, in *CreateOwnerRequest, opts ...grpc.CallOption) (*CreateOwnerResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	GetUsersByID(ctx context.Context, in *GetUsersByIDRequest, opts ...grpc.CallOption) (*GetUsersByIDResponse, error)
	MultiplePermissionsEdit(ctx context.Context, in *MultiplePermissionsEditRequest, opts ...grpc.CallOption) (*MultiplePermissionsEditResponse, error)
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) CreateOwner(ctx context.Context, in *CreateOwnerRequest, opts ...grpc.CallOption) (*CreateOwnerResponse, error) {
	out := new(CreateOwnerResponse)
	err := c.cc.Invoke(ctx, "/pb.UsersService/CreateOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/pb.UsersService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUsersByID(ctx context.Context, in *GetUsersByIDRequest, opts ...grpc.CallOption) (*GetUsersByIDResponse, error) {
	out := new(GetUsersByIDResponse)
	err := c.cc.Invoke(ctx, "/pb.UsersService/GetUsersByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) MultiplePermissionsEdit(ctx context.Context, in *MultiplePermissionsEditRequest, opts ...grpc.CallOption) (*MultiplePermissionsEditResponse, error) {
	out := new(MultiplePermissionsEditResponse)
	err := c.cc.Invoke(ctx, "/pb.UsersService/MultiplePermissionsEdit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, "/pb.UsersService/CheckAccess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	CreateOwner(context.Context, *CreateOwnerRequest) (*CreateOwnerResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	GetUsersByID(context.Context, *GetUsersByIDRequest) (*GetUsersByIDResponse, error)
	MultiplePermissionsEdit(context.Context, *MultiplePermissionsEditRequest) (*MultiplePermissionsEditResponse, error)
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
}

// UnimplementedUsersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsersServiceServer struct {
}

func (*UnimplementedUsersServiceServer) CreateOwner(ctx context.Context, req *CreateOwnerRequest) (*CreateOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOwner not implemented")
}
func (*UnimplementedUsersServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUsersServiceServer) GetUsersByID(ctx context.Context, req *GetUsersByIDRequest) (*GetUsersByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsersByID not implemented")
}
func (*UnimplementedUsersServiceServer) MultiplePermissionsEdit(ctx context.Context, req *MultiplePermissionsEditRequest) (*MultiplePermissionsEditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiplePermissionsEdit not implemented")
}
func (*UnimplementedUsersServiceServer) CheckAccess(ctx context.Context, req *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccess not implemented")
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_CreateOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CreateOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UsersService/CreateOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CreateOwner(ctx, req.(*CreateOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UsersService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUsersByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetUsersByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UsersService/GetUsersByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetUsersByID(ctx, req.(*GetUsersByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_MultiplePermissionsEdit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplePermissionsEditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).MultiplePermissionsEdit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UsersService/MultiplePermissionsEdit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).MultiplePermissionsEdit(ctx, req.(*MultiplePermissionsEditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UsersService/CheckAccess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOwner",
			Handler:    _UsersService_CreateOwner_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UsersService_GetUser_Handler,
		},
		{
			MethodName: "GetUsersByID",
			Handler:    _UsersService_GetUsersByID_Handler,
		},
		{
			MethodName: "MultiplePermissionsEdit",
			Handler:    _UsersService_MultiplePermissionsEdit_Handler,
		},
		{
			MethodName: "CheckAccess",
			Handler:    _UsersService_CheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users-service.proto",
}
