export enum OtpTypeEnum {
  SIGN_UP = 'SIGN_UP',
  RESET_PASSWORD = 'RESET_PASSWORD',
  RESET_PHONE = 'RESET_PHONE',
  RESET_EMAIL = 'RESET_EMAIL',
  SIGN_VERIFICATION_DOCUMENTS = 'SIGN_VERIFICATION_DOCUMENTS',
  CONFIRM_TRANSACTION = 'CONFIRM_TRANSACTION',
}
