ARG BASE_IMAGE
FROM $BASE_IMAGE AS build


FROM nginx:alpine AS server

COPY ./infra/prod/nginx/default.web.conf /etc/nginx/conf.d/default.conf
COPY --chown=nginx:nginx --from=build /app/storybook-static /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

